#pragma once
#include <string>

#include "I18nKeys.h"

// THIS FILE IS AUTO-GENERATED BY gen_i18n.py. DO NOT EDIT.

namespace i18n_strings {

extern const char* const STRINGS_EN[];
extern const char* const STRINGS_KO[];

}  // namespace i18n_strings
